
@hostName = http://127.0.0.1:3030
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.j9ISYNXLDURR2jAVf8s1brNCqDOavJYgI4vkGa3u9IY

### canva
GET {{hostName}}/canva
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{hostName}}/canva
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "tieu_de": "Tieu de 1"
}

###
GET {{hostName}}/canva/1
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET {{hostName}}/canva/1/session
Authorization: Bearer {{token}}
Content-Type: application/json

###
PUT {{hostName}}/canva/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "tieu_de": "Tieu sau khi update"
}

###
DELETE {{hostName}}/canva/1
Authorization: Bearer {{token}}
Content-Type: application/json
