

@hostName = http://127.0.0.1:3030
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.j9ISYNXLDURR2jAVf8s1brNCqDOavJYgI4vkGa3u9IY


###
GET {{hostName}}/cau_hoi
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET {{hostName}}/cau_hoi/4
Authorization: Bearer {{token}}
Content-Type: application/json

###
POST {{hostName}}/cau_hoi/4/lua_chon
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "noi_dung": "test inster 1", 
    "dung": true
}

###
DELETE {{hostName}}/cau_hoi/4/lua_chon/1
Authorization: Bearer {{token}}
Content-Type: application/json

