
@hostName = http://127.0.0.1:3030
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.j9ISYNXLDURR2jAVf8s1brNCqDOavJYgI4vkGa3u9IY

###
GET {{hostName}}/player
Authorization: Bearer {{token}}

###
GET {{hostName}}/player/e5f6g7h8-i9j0-k1l2-m3n4-o5p6q7r8s9t0
Authorization: Bearer {{token}}

###
POST {{hostName}}/player
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "uuid": "{{$guid}}",
    "session_id": 4,
    "name": "create test",
    "email": "ab@a.com",
    "std": "0347402306",
    "thoi_gian_vao": "{{$datetime iso8601}}"
}

###
PUT {{hostName}}/player/e5f6g7h8-i9j0-k1l2-m3n4-o5p6q7r8s9t0
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "test update 1"
}

###
DELETE {{hostName}}/player/e5f6g7h8-i9j0-k1l2-m3n4-o5p6q7r8s9t1
Authorization: Bearer {{token}}

