services:
  reactjs:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://127.0.0.1:3030

  nodejs:
    build: ./backend
    ports:
      - "3030:3030"
    environment:
      - PORT=3030
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=root1772005
      - DB_NAME=clone_kaboot
      - DB_PORT=3306
      - JWT_SECRET=<Token_CyberSoft>
      - JWT_EXPIRATION=1m
      - REFRESH_TOKEN_SECRET=GDUIT
      - REFRESH_TOKEN_EXPIRATION=365d



